import Layout from "@/components/providers/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import AuthProvider from "@/components/providers/AuthProvider";
import { Toaster } from "sonner";
import { GeistSans } from "geist/font/sans";
import GoogleMapsProvider from "@/components/providers/GoogleMapsProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
console.log("Hello world");
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable}`}>
        <AuthProvider>
          <GoogleMapsProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Layout>
                {children}
                <Toaster richColors position="top-center" />
              </Layout>
            </ThemeProvider>
          </GoogleMapsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
