import Layout from "@/components/providers/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import NextUIProvider from "@/components/providers/next-ui-provider";
import AuthProvider from "@/components/providers/AuthProvider";
import { Toaster } from "sonner";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable}`}>
        <AuthProvider>
          <NextUIProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Layout>
                {children}
                <Toaster richColors />
              </Layout>
            </ThemeProvider>
          </NextUIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
